#----------------------------------------------------------------
# Autor: Juan Felipe Gómez López
# Programa: Makefile
# Fecha: 6 de noviembre 2025
# Tema: Automatizacion de compilación y limpieza en el directorio
# ---------------------------------------------------------------


GCC = gcc
FLAGS = -fopenmp -lm

PROGRAMAS = lab01 lab02 lab03 lab04

lab01:
	$(GCC) $@.c -o $@ $(FLAGS)

lab02:
	$(GCC) $@.c -o $@ $(FLAGS)

lab03:
	$(GCC) $@.c -o $@ $(FLAGS)

lab04:
	$(GCC) $@.c -o $@ $(FLAGS)

clean:
	$(RM) $(PROGRAMAS)
