CC = gcc
CFLAGS = -Wall -g

PROGS = challenge01 challenge02 challenge03 challenge04 challenge05

all: $(PROGS)

challenge01: challenge01.c
	$(CC) $(CFLAGS) -o challenge01 challenge01.c

challenge02: challenge02.c
	$(CC) $(CFLAGS) -o challenge02 challenge02.c

challenge03: challenge03.c
	$(CC) $(CFLAGS) -o challenge03 challenge03.c

challenge04: challenge04.c
	$(CC) $(CFLAGS) -o challenge04 challenge04.c

challenge05: challenge05.c
	$(CC) $(CFLAGS) -o challenge05 challenge05.c

clean:
	rm -f $(PROGS) *.o

